package com.duggustore.app.data.repository

import com.duggustore.app.data.model.Category
import com.duggustore.app.data.remote.SessionManager
import com.duggustore.app.data.remote.SupabaseService
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put

private val json = Json { ignoreUnknownKeys = true; coerceInputValues = true }

class CategoryRepository {

    private fun token(): String? = SessionManager.getAccessToken()

    /** Writable columns only — `id` is generated by the database. */
    private fun body(category: Category): JsonObject = buildJsonObject {
        put("name", category.name)
        category.iconUrl?.let { put("icon_url", it) }
        put("color_hex", category.colorHex)
        put("sort_order", category.sortOrder)
        put("is_active", category.isActive)
    }

    suspend fun getAllCategories(): Result<List<Category>> {
        return try {
            val list = SupabaseService.selectAll("categories", token())
            Result.success(
                list.map { json.decodeFromString(Category.serializer(), it.toString()) }
                    .sortedBy { it.sortOrder }
            )
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    suspend fun createCategory(category: Category): Result<Unit> {
        return try {
            SupabaseService.insert("categories", body(category).toString(), token())
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    suspend fun updateCategory(category: Category): Result<Unit> {
        return try {
            SupabaseService.update("categories", category.id, body(category).toString(), token())
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    suspend fun deleteCategory(id: String): Result<Unit> {
        return try {
            SupabaseService.delete("categories", id, token())
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}
